apiVersion: v1
kind: Pod
metadata:
  name: interactive
spec:
  containers:
    - name: gpu-container
      image: docker.io/ctvqfq/bunny_ai:kube_tutorial
      command: ["jupyter", "lab"]
      resources:
        limits:
        nvidia.com/gpu: "2"
        memory: "8G"
        cpu: "4"
      volumeMounts:
        - name: results
          mountPath: /develop/results
        - name: data
          mountPath: /develop/data

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
    - name: results
      persistentVolumeClaim:
        claimName: results

  restartPolicy: Never

apiVersion: v1
kind: Pod
metadata:
    name: notebook
spec:
    containers:
        restartPolicy: Never

        - name: gpu-container
            image: docker.io/ctvqfq/bunny_ai:kube_tutorial
            command: ["jupyter", "lab"]

        resources:
            limits:
                nvidia.com/gpu: "2"
                memory: "8G"
                cpu: "4"


