apiVersion: batch/v1
kind: Job
metadata:
  name: gen-all-demo
spec:
  template:
    spec:
      containers:
        - name: gen-all-demo
          image: docker.io/ctvqfq/bunny_ai:demo-1.0
          command: ["/bin/sh", "-c"]
          args: ["git clone https://github.com/slane-winter/kubenetes.git .; cd /develop/code/src/generation; python gen_data.py; python gen_models.py"]
          resources:
            limits:
              memory: 32G
              cpu: 16
            requests:
              memory: 16G
              cpu: 16
          volumeMounts:
            - name: demo-data
              mountPath: /develop/data

      volumes:
        - name: demo-data
          persistentVolumeClaim:
            claimName: demo-data

      restartPolicy: Never
