apiVersion: v1
kind: Pod
metadata:
  name: monitor
spec:
  containers:
    - name: monitor
      image: docker.io/ctvqfq/bunny_ai:demo
      stdin: True
      tty: True
      resources:
        limits:
          memory: 8G
          cpu: 6
        requests:
          memory: 6G
          cpu: 6
      volumeMounts:
        - name: demo-data
          mountPath: /develop/data
  volumes:
    - name: demo-data
      persistentVolumeClaim:
        claimName: demo-data

  restartPolicy: Never

