apiVersion: v1
kind: Pod
metadata:
  name: monitor
spec:
  containers:
    - name: monitor
      image: docker.io/ctvqfq/bunny_ai:demo-1.0
      stdin: True
      tty: True
      resources:
        limits:
          memory: 8G
          cpu: 6
          nvidia.com/gpu: 2
        requests:
          memory: 6G
          cpu: 6
          nvidia.com/gpu: 2
      volumeMounts:
        - name: demo-data
          mountPath: /develop/data
        - name: demo-results
          mountPath: /develop/results

  volumes:
    - name: demo-data
      persistentVolumeClaim:
        claimName: demo-data
    - name: demo-results
      persistentVolumeClaim:
        claimName: demo-results

  restartPolicy: Never

